### ISSUE TITLE
debox.Map.update() speed can be improved

### ISSUE THREAD

**Issue by JD557** [non/debox#23]
Hi, I've believe that it's possible to improve the speed of `debox.Map.update` by using a `freeBlock` accumulator (see my pull request #22) and only updating the map when it finds a block with `status == 0`, therefore avoiding the `!contains` check.

However, I think it would be better to remove the `!contains` check completely and move that responsibility to the `remove` operation, by stopping the loop only when it finds a block with `status == 0`. I believe this would be better, as updates are more common than removals IMO.

I'm okay with sending a pull request with this changes, but I would like some feedback on what's approach do you think it's better.

**Comment by non** [comment]
I like the `freeBlock` approach you used in #22.

I'd be interested to see a PR with either change, especially if we can show an improvement for update speeds. I agree that updates are more common than removals for most work loads.
